// @ts-check
"use strict";

const ALL_LOCALES = [
	"en_US",
	"en_GB",
	"de_DE",
	"es_ES",
	"es_MX",
	"fr_FR",
	"fr_CA",
	"it_IT",
	"ja_JP",
	"ko_KR",
	"pt_BR",
	"pt_PT",
	"ru_RU",
	"zh_CN",
	"zh_TW",
	"nl_NL",
	"bg_BG",
	"cs_CZ",
	"da_DK",
	"el_GR",
	"fi_FI",
	"hu_HU",
	"id_ID",
	"nb_NO",
	"pl_PL",
	"sk_SK",
	"sv_SE",
	"tr_TR",
	"uk_UA",
];

/** Maps Minecraft locale codes to API language codes (Google / ISO 639).
 * @type {Record<string, string>}
 */
const LOCALE_TO_API_CODE = {
	en_US: "en",
	en_GB: "en-GB",
	de_DE: "de",
	es_ES: "es",
	es_MX: "es",
	fr_FR: "fr",
	fr_CA: "fr-CA",
	it_IT: "it",
	ja_JP: "ja",
	ko_KR: "ko",
	pt_BR: "pt-BR",
	pt_PT: "pt-PT",
	ru_RU: "ru",
	zh_CN: "zh-CN",
	zh_TW: "zh-TW",
	nl_NL: "nl",
	bg_BG: "bg",
	cs_CZ: "cs",
	da_DK: "da",
	el_GR: "el",
	fi_FI: "fi",
	hu_HU: "hu",
	id_ID: "id",
	nb_NO: "no",
	pl_PL: "pl",
	sk_SK: "sk",
	sv_SE: "sv",
	tr_TR: "tr",
	uk_UA: "uk",
};

/** @type {Record<string, string>} */
const LOCALE_NAMES = {
	en_US: "English (US)",
	en_GB: "English (UK)",
	de_DE: "German",
	es_ES: "Spanish (Spain)",
	es_MX: "Spanish (Mexico)",
	fr_FR: "French (France)",
	fr_CA: "French (Canada)",
	it_IT: "Italian",
	ja_JP: "Japanese",
	ko_KR: "Korean",
	pt_BR: "Portuguese (Brazil)",
	pt_PT: "Portuguese (Portugal)",
	ru_RU: "Russian",
	zh_CN: "Chinese (Simplified)",
	zh_TW: "Chinese (Traditional)",
	nl_NL: "Dutch",
	bg_BG: "Bulgarian",
	cs_CZ: "Czech",
	da_DK: "Danish",
	el_GR: "Greek",
	fi_FI: "Finnish",
	hu_HU: "Hungarian",
	id_ID: "Indonesian",
	nb_NO: "Norwegian (Bokmaal)",
	pl_PL: "Polish",
	sk_SK: "Slovak",
	sv_SE: "Swedish",
	tr_TR: "Turkish",
	uk_UA: "Ukrainian",
};

const MAX_RETRIES = 5;

module.exports = { ALL_LOCALES, LOCALE_TO_API_CODE, LOCALE_NAMES, MAX_RETRIES };
